




.build/uno/src/Vultrasound_ledge.cpp : src/Vultrasound_ledge.ino
	@mkdir -p .build/uno/src
	@echo src/Vultrasound_ledge.ino
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/Vultrasound_ledge.cpp
	@true

