




.build/uno/src/TestServoSpeed.cpp : src/TestServoSpeed.ino
	@mkdir -p .build/uno/src
	@echo src/TestServoSpeed.ino
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/TestServoSpeed.cpp
	@true

