




.build/uno/src/Vultrasound.cpp : src/Vultrasound.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/Vultrasound.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/Vultrasound.cpp
	@true

