




.build/uno/src/StartResetIndicator.cpp : src/StartResetIndicator.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/StartResetIndicator.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/StartResetIndicator.cpp
	@true

